crop/urls.py
from django.urls import path

from crop.views.cropDetails import CropDetails
from crop.views.cropCreator import CropCreator
from taxonomy.views.genus import Genus
from taxonomy.views.species import Species
from crop.views.cropForm import CropForm

urlpatterns = [
    path("add", CropForm.as_view(), name="addCrops"),
    path("", CropDetails.as_view(), name="listCrops"),
    path("create", CropCreator.as_view(), name="addCrop"),
    path("species/create", Species.as_view(), name="addSpecies"),
    path("genus/create", Genus.as_view(), name="addGenus"),
]

farm/urls.py
from django.urls import path

from farm.views.farmApi import FarmApi
from farm.views.plotRemover import PlotRemover
from farm.views.farmCreator import FarmCreator
from farm.views.farmOverview import FarmOverview
from farm.views.plotCreator import PlotCreator

urlpatterns = [
    path("", FarmApi.as_view(), name="my-farms"),
    path("/<slug:slug>", FarmApi.as_view(), name="my-farms"),
    path("old/create", FarmCreator.as_view(), name="createFarm"),
    path("old/<slug:slug>", FarmOverview.as_view(), name="farmOverview"),
    path("old/<slug:slug>/plots", PlotCreator.as_view(), name="plotOverview"),
    path("old/<slug:slug>/plots/create", PlotCreator.as_view(), name="plotCreator"),
    path("old/<slug:slug>/plots/delete", PlotRemover.as_view(), name="plotCreator"),
]

soli/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework import routers

from farm.views import farmApi
from farm.views.farmApi import FarmApi

from soli import settings

urlpatterns = [
    path("", include("account.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("plot/", include("plot.urls")),
    path("myfarms/", include("farm.urls")),
    path("calendar/", include("schedule.urls")),
    path("seedbank/", include("seedbank.urls")),
    path("herd/", include("herd.urls")),
    path("admin/crop/", include("crop.urls")),
    path("crop/", include("crop.urls")),
    path("layout/", include(("layout.urls"))),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farm/models/farm.py
from datetime import date, datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.utils.text import slugify

from climate.models.climate import Climate
from geometry.models.point import Point

YEAR_CHOICES = [(year, year) for year in range(1900, date.today().year + 1)]


class Farm(models.Model):
    class Meta:
        db_table = "farm"
        app_label = "farm"
        unique_together = ["farmer", "name"]

    farmer = models.ForeignKey(User, on_delete=CASCADE)
    location = models.ForeignKey(Point, on_delete=CASCADE, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    name = models.CharField(max_length=128, default=f"My Farm")
    logo = models.ImageField(null=True, blank=True, upload_to="logos")
    climate = models.ForeignKey(Climate, on_delete=CASCADE, blank=True, null=True)
    year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.now().year)
    slug = models.SlugField(unique=False)
    phone = models.BigIntegerField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=128, null=True, blank=True)
    address2 = models.CharField(max_length=128, null=True, blank=True)
    city = models.CharField(max_length=128, null=True, blank=True)
    state = models.CharField(max_length=128, null=True, blank=True)
    zip = models.IntegerField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):

        established = f"(est. {self.year})" if self.year is not None else ""
        return f"{self.name} {established}"

farm/models/plot.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE

from farm.models.farm import Farm
from geometry.models.point import Point
from geometry.models.shape import POLYGON, Shape
from farm.models.validation.plotTypes import TYPES


class Plot(models.Model):
    class Meta:
        db_table = "plot"
        app_label = "plot"

    name = models.CharField(max_length=128, blank=True, default="Unnamed Plot")
    farm = models.ForeignKey(Farm, on_delete=CASCADE)
    farmer = models.ForeignKey(User, on_delete=CASCADE)
    shape = models.ForeignKey(Shape, null=True, default=None, on_delete=CASCADE)
    description = models.CharField(max_length=1024, blank=True, default="")
    parent = models.ForeignKey("self", blank=True, null=True, on_delete=CASCADE)
    type = models.CharField(
        choices=TYPES, max_length=1, blank=True, null=True, default=None
    )

    def save(self):
        if self.shape is not None:
            self.shape.save()

        if self.points is not None:
            for point in self.points:
                point.save()

        super(Plot, self).save()

    def __str__(self):
        return self.name

    def update_boundaries(self, area, vertexes):
        self.shape = Shape(type=POLYGON, area=area)
        self.points = [
            Point(shape=self.shape, lat=point["lat"], long=point["lng"])
            for point in vertexes
        ]

    def delete(self):
        if self.shape:
            self.shape.delete()

        super(Plot, self).delete()

farm/models/plotDetailsList.py
from farm.models.farm import Farm
from geometry.models.point import Point
from geometry.models.shape import Shape
from farm.models.plot import Plot
from farm.models.plotDetails import PlotDetails


class PlotDetailsList:
    plotDetails = []

    def __init__(self, farmer, farm=None):
        print("here")
        self.plotDetails = []
        self.farmer = farmer
        self.farm = (
            farm if farm is not None else Farm.objects.filter(farmer=self.farmer)
        )

    def getPlotDetailsByPlotName(self, name):

        if self.farmer is not None:
            self.setPlotDetailsFromPoints(
                Point.objects.filter(
                    plot__in=Plot.objects.filter(farmer=self.farmer, name=name)
                )
            )

        return self

    def getPlotDetailsForUser(self):
        if self.farmer is not None:
            plots = Plot.objects.filter(farmer=self.farmer)
            self.setPlotDetailsFromPlots(plots)

        return self

    def getParentPlots(self):
        if self.farmer is not None:
            plots = Plot.objects.filter(farmer=self.farmer, parent__isnull=True)
            self.setPlotDetailsFromPlots(plots)

        return self

    def setPlotDetailsFromPlots(self, plots):
        points = Point.objects.filter(shape__in=Shape.objects.filter(plot__in=plots))

        for plot in plots:
            if plot.parent is None:
                children = plots.filter(parent=plot)
                childDetails = [
                    PlotDetails(plot=child, points=points.filter(shape=child.shape))
                    for child in children
                ]

                self.plotDetails.append(
                    PlotDetails(
                        farmer=self.farmer,
                        farm=self.farm,
                        plot=plot,
                        points=points.filter(shape=plot.shape),
                        children=childDetails,
                    )
                )

    def jsonify(self):
        return [plotDetail.jsonify() for plotDetail in self.plotDetails]

farm/forms/farmForm.py
from django import forms

from farm.models.farm import Farm
from formTemplates.inputFields import (
    createImageUpload,
    createTextInput,
    createYearInput,
    createTextArea,
)
from geometry.models.point import Point


class FarmForm(forms.ModelForm):
    location = None
    farmer = None

    class Meta:
        model = Farm
        fields = ["name", "logo", "year", "description"]

        widgets = {
            "name": createTextInput(placeholder="Farm Name", id="plot-name"),
            "logo": createImageUpload(id="plot-logo"),
            "year": createYearInput(),
            "description": createTextArea(),
        }

    def saveFarm(self, climate):
        farm = self.save(commit=False)
        farm.location = self.location
        farm.farmer = self.farmer
        farm.climate = climate
        farm.save()

        return farm

    def setFarmHeadquarters(self):
        coordinates = self.getCoordinates()
        if len(coordinates) == 2:
            self.location = Point(lat=coordinates[0], long=coordinates[1])
            self.location.save()

    def getCoordinates(self):
        coordinates = []

        try:
            location = self.data["location"].split(",")
            if len(location) == 2:
                coordinates = [float(coord) for coord in location]
        except Exception as e:
            print(e)

        return coordinates

soli/aria/forms/farm.py
from django import forms

from aria.forms.templates.templates import createImageUpload, createTextInput
from aria.models.farm import Farm


class CreateFarmForm(forms.ModelForm):
    class Meta:
        model = Farm
        fields = [
            "name",
            "logo"
        ]

        widgets = {
            "name": createTextInput(placeholder="Farm Name", id="farm-name"),
            "logo": createImageUpload(id="farm-logo")
        }

farm/views.py
# Create your views here.

farm/views/farmApi.py
from rest_framework.response import Response
from rest_framework.views import APIView

from farm.models.farm import Farm
from farm.serializers.farmSerializer import FarmSerializer


class FarmApi(APIView):
    farmer = None

    def get(self, request, format=None):

        self.farmer = request.user

        farms = Farm.objects.filter(farmer=self.farmer)
        farm_serializer = FarmSerializer(farms, many=True)

        return Response(farm_serializer.data)

farm/views/farmCreator.py
from django.http import HttpResponseRedirect

from climate.forms.climateForm import ClimateForm
from farm.forms.farmForm import FarmForm

from soli.views.authenticatedPageView import AuthenticatedPageView


class FarmCreator(AuthenticatedPageView):
    farm = None
    climate = None
    request = None
    user = None
    location = []
    context = {}

    def get(self, request):
        self.construct(request)

        if self.request.user.id is not None:
            self.context["farmForm"] = FarmForm()
            self.context["climateForm"] = ClimateForm()
        return self.render("createFarm.html")

    def post(self, request):
        self.construct(request)

        if self.request.user.id is not None:
            self.createFarm()
            self.createFarmClimate()

            if self.farm.is_valid():
                self.saveAllFarmData()

        return HttpResponseRedirect("/")

    def farmDataIsValid(self):

        valid = self.farm.is_valid() and self.climate.is_valid()

        if not valid:
            print(self.farm.errors)
            print(self.climate.errors)

        return valid

    def saveAllFarmData(self):
        self.climate = self.climate.saveClimate(self.farm)
        self.farm = self.farm.saveFarm(self.climate)

    def createFarmClimate(self):
        self.climate = ClimateForm(self.request.POST)
        self.climate.setFrostDates()

    def createFarm(self):
        self.farm = FarmForm(self.request.POST)
        self.farm.setFarmHeadquarters()
        self.farm.farmer = self.request.user

farm/views/farmOverview.py
from farm.models.farm import Farm
from soli.views.authenticatedPageView import AuthenticatedPageView


class FarmOverview(AuthenticatedPageView):
    farm = None
    request = None
    context = {}

    def get(self, request, slug):

        self.construct(request)
        self.context["farm"] = Farm.objects.filter(slug=slug, farmer=request.user).get()

        self.context["cards"] = ["map", "contact", "overview"]

        return self.render("farm_overview.html")

farm/views/plot.py
import json

from django.http import JsonResponse
from django.shortcuts import render

from farm.models.farm import Farm
from geometry.models.shape import Shape
from farm.models.plotDetails import PlotDetails
from farm.models.plotDetailsList import PlotDetailsList
from farm.models.validation.plotTypes import TYPES


def createPlot(request):
    page = ""
    context = {}
    if request.user.id is not None:
        plotDetailsList = PlotDetailsList(request.user)
        farm = Farm.objects.filter(farmer=request.user).first()

        if request.method == "GET":
            page = "plot/create/plot.html"
            context = {
                "plots": plotDetailsList.getParentPlots().jsonify(),
                "plot": farm,
            }

        elif request.method == "POST":
            return addPlotDetails(request)

    return render(request, page, context)


def addPlotDetails(request):
    if request.user.id is not None:
        plotDetailsList = PlotDetailsList(farmer=request.user)

        context = {
            "plots": plotDetailsList.getPlotDetailsForUser().jsonify(),
            "plotTypes": TYPES,
        }
    else:
        context = {}

    return render(request, "plot/create/plotdetails.html", context)


def createPlotAjax(request):
    response = {"errors": []}
    if request.user and request.is_ajax() and request.method == "POST":
        plotDetails = createNewPlot(request)
        response["plot"] = plotDetails.plot.id

        if "returnPage" in request.POST:
            context = {"child": plotDetails.plot}

            return render(request, request.POST["returnPage"] + ".html", context)
        else:
            return JsonResponse(response)


def createNewPlot(request):
    plotDetails = PlotDetails(request=request)
    plotDetails.savePlotAndPoints()

    return plotDetails


def deletePlotsAjax(request):
    response = {"errors": []}

    if request.is_ajax() and request.method == "POST":
        plots = json.loads(request.POST["plots"])
        deleted, rows = Shape.objects.filter(plot__in=plots).delete()

        if deleted == 0:
            response["errors"] += f"Could not delete plots: {plots}"

    return JsonResponse(response)

farm/views/plotCreator.py
import json

from django.shortcuts import render

from farm.models.farm import Farm
from farm.models.plot import Plot
from farm.models.plotDetailsList import PlotDetailsList
from soli.views.authenticatedPageView import AuthenticatedPageView


class PlotCreator(AuthenticatedPageView):
    context = {}
    params = {}

    def get(self, request, slug):

        self.construct(request)

        farm = Farm.objects.filter(slug=slug, farmer=request.user).get()
        plots = PlotDetailsList(request.user, farm=farm)

        self.context["farm"] = farm
        self.context["plots"] = plots.getParentPlots().jsonify()

        return self.render("plot_overview.html")

    def post(self, request, slug):
        self.params = request.POST
        farm = Farm.objects.filter(
            slug=slug, farmer=request.user, id=self.params["farm"]
        ).get()

        area = self.params["area"]
        vertexes = json.loads(self.params["points"])[0]

        if "plot" in self.params:
            plot = Plot.objects.filter(
                id=self.params["plot"], farmer=request.user
            ).get()
            plot.name = self.params["name"]
            plot.description = self.params["description"]
        else:
            plot = Plot(farmer=request.user, farm=farm)

        plot.update_boundaries(area, vertexes)
        plot.save()
        self.context["plot"] = plot

        return render(self.request, "plot_sidebar_detail.html", self.context)

farm/views/plotRemover.py
import json

from django.http import JsonResponse

from farm.models.plot import Plot
from soli.views.authenticatedPageView import AuthenticatedPageView


class PlotRemover(AuthenticatedPageView):
    def get(self, request):
        self.construct(request)
        pass

    def post(self, request, slug):
        response = {"errors": []}

        self.construct(request)
        plots = json.loads(self.request.POST["plots"])
        deleted, rows = Plot.objects.filter(
            id__in=plots, owner=self.user, farm=self.request.POST["farm"]
        ).delete()

        if rows == 0:
            response["errors"] += f"Could not delete plots: {plots}"

        return JsonResponse(response)

farm/templates/createFarm.html
{% extends 'pageLayout.html' %}
{% load static %}
    
{% block includes %}
    {% include "maps.html" %}
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/maps/initmap.js' %}" type="text/javascript"></script>
    <script src="{% static './farm/js/createFarm.js' %}" type="text/javascript"></script>
{% endblock %}

{% block pageContent %}
    <div class="row">
        <div class="col-lg">
            <form id="farm-form" class="card mb-4" method="POST">
                {% csrf_token %}
                <div class="card-header">
                    <h3>
                        Your Farm
                    </h3>
                </div>
                <div class="card-body">
                    <div class="input-group">
                        {{ farmForm.name }}
                        <div class="input-group-append">
                            <span class="input-group-text">Est.</span>
                        </div>
                        {{ farmForm.year }}
                        <div class="custom-file">
                            {{ farmForm.logo }}
                            <label class="custom-file-label" for="farm-logo">Logo</label>
                        </div>
                        <input type="hidden" name="location" id="id_location">
                    </div>
                </div>
                <div class="card-body row">
                    <div class="col-lg">
                        <h4>Headquarters</h4>
                        <div class="map map-md" id="map">
                        </div>
                    </div>
                    <div class="col-lg">
                        <h4>Farm Details</h4>
                        <div class="input-group mb-3">
                            {{ farmForm.description }}
                        </div>
                        <div class="input-group mb-3">
                            {{ climateForm.zone }}
                        <div class="input-group mb-3">
                        <div>
                            {{ climateForm.lastFrost }}
                            {{ climateForm.firstFrost }}
                        </div>
                        <input class="btn btn-primary pull-right" type="submit" value="OK">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

farm/templates/createFarmBanner.html
{% extends 'uiElements/card.html' %}

{% block header %}
    <h4>
        <a class="btn btn-sm btn-primary btn-circle stretched-link" href="{% url 'createFarm' %}">+</a>
        Create a Farm
    </h4>
{% endblock %}

{% block content %}
    <p>Your farms are the broadest level of organization.  They contain all information about the fields, gardens, and animals.</p>
{% endblock %}

farm/templates/farmCard.html
{% extends 'uiElements/card.html' %}

{% block header %}
    <a id="{{ farm.name }}" href="{% url 'farmOverview' farm.slug %}" class="text-decoration-none d-sm-flex align-items-center justify-content-between mb-4">
        {% if farm.logo %}
            <div class="col-2 mx-auto">
                <img class="img-fluid" src="{{ farm.logo.url }}" alt="{{ farm.name }} Logo"/>
            </div>
        {% endif %}
        <div class="col-md-12 col-lg-10 text-center text-lg-left align-self-center">
            <h2>
                {{ farm }}
            </h2>
        </div>
    </a>
{% endblock %}

{% if cards %}
    {% block content %}
        <div class="row">
            {% if "overview" in cards %}
                {% if farm.description %}
                    {% include 'uiElements/card.html' with id="description" size="lg" content=farm.description %}
                {% endif %}
                {% if climate.zone %}
                    {% include "climate/templates/climate_overview.html" with size="md" climate=farm.climate %}
                {% endif %}
            {% endif %}

            {% if "contact" in cards %}
                {% if farm.address or farm.phone or farm.email %}
                    {% include 'contactCard.html' with size="md" farm=farm header="contact" id="contact"%}
                {% endif %}
            {% endif %}

            {% if "map" in cards %}
                <div class="row">
                     <div id="farm-map-{{ farm.id }}" class="col-md map map-md" data-farmId="{{ farm.id }}" data-lat="{{ farm.location.lat }}" data-long="{{ farm.location.long }}">
                     </div>
                </div>
            {% endif %}
        </div>

    {% endblock %}
{% endif %}

farm/templates/farmContact.html
{% extends 'uiElements/card.html' %}

{% block content %}
<div class="card-body contact text-center">
    <ul class="text-lg-left list-unstyled">
        {% if farm.address %}
            <li>
                <p><i class="fas fa-map-marker-alt pr-1"></i>{{ farm.address }}</p>
                {% if farm.address2 %}
                    <p>{{ farm.address2 }}</p>
                {% endif %}
                {% if farm.city and farm.state %}
                    <p>{{ farm.city}}, {{ farm.state }}
                {% elif farm.city %}
                    <p>{{ farm.city }}</p>
                {% elif farm.state %}
                    <p>{{ farm.state }}</p>
                {% endif %}
            </li>
        {% endif %}
        {% if farm.phone %}
            <li>
                <p><i class="fas fa-phone pr-1"></i>{{ farm.phone }}</p>
            </li>
        {% endif %}
        {% if farm.email %}
            <li>
                <p><i class="fas fa-envelope pr-1"></i>{{ farm.email }}</p>
            </li>
        {% endif %}
    </ul>
    <hr class="hr-light my-4">
    <ul class="list-inline text-center list-unstyled">
        <li class="list-inline-item">
            <a class="p-2 fa-lg tw-ic">
                <i class="fab fa-twitter"></i>
            </a>
         </li>
        <li class="list-inline-item">
            <a class="p-2 fa-lg li-ic">
                <i class="fab fa-linkedin-in"> </i>
            </a>
        </li>
        <li class="list-inline-item">
            <a class="p-2 fa-lg ins-ic">
                <i class="fab fa-instagram"> </i>
            </a>
        </li>
    </ul>
</div>
{% endblock %}

farm/templates/farmOverview.html
{% extends 'pageLayout.html' %}
{% load static %}
    
{% block includes %}
    {% include "maps.html" %}
{% endblock %}

{% block javascript %}
    <script src="{% static './farm/js/farmOverview.js' %}" type="text/javascript"></script>
{% endblock %}

{% block pageContent %}
    {{ farm.location.getCoordinates  | json_script:"farm-location" }}
    {% include "farm/templates/farmCard.html" with size="full" farm=farm cards=cards %}
{% endblock %}

farm/templates/farm_card.html
{% extends 'uiElements/card.html' %}

{% block header %}
    {% include 'farm_header.html' with farm=farm %}
{% endblock %}

{% if cards %}
    {% block content %}
        <div class="row">
            {% if "overview" in cards %}
                {% if farm.description %}
                    {% include 'uiElements/card.html' with id="description" size="lg" content=farm.description %}
                {% endif %}
                {% if climate.zone %}
                    {% include "climate/templates/climate_overview.html" with size="md" climate=farm.climate %}
                {% endif %}
            {% endif %}

            {% if "contact" in cards %}
                {% if farm.address or farm.phone or farm.email %}
                    {% include 'contactCard.html' with size="md" farm=farm header="contact" id="contact"%}
                {% endif %}
            {% endif %}

            {% if "map" in cards %}
                <div class="row">
                     <div id="farm-map-{{ farm.id }}" class="col-md map map-md" data-farmId="{{ farm.id }}" data-lat="{{ farm.location.lat }}" data-long="{{ farm.location.long }}">
                     </div>
                </div>
            {% endif %}
        </div>

    {% endblock %}
{% endif %}

farm/templates/farm_header.html
<a id="{{ farm.name }}" href="{% url 'farmOverview' farm.slug %}" class="text-decoration-none d-sm-flex align-items-center justify-content-between mb-4">
    {% if farm.logo %}
        <div class="col-2 mx-auto">
            <img class="img-fluid" src="{{ farm.logo.url }}" alt="{{ farm.name }} Logo"/>
        </div>
    {% endif %}
    <div class="col-md-12 col-lg-10 text-center text-lg-left align-self-center">
        <h2>
            {{ farm }}
        </h2>
    </div>
</a>

farm/templates/farm_overview.html
{% extends 'pageLayout.html' %}
{% load static %}
    
{% block includes %}
    {% include "maps.html" %}
{% endblock %}

{% block javascript %}
    <script src="{% static './farm/js/farmOverview.js' %}" type="text/javascript"></script>
{% endblock %}

{% block pageContent %}
    {{ farm.location.getCoordinates | json_script:"farm-location" }}
    {% include "farm/templates/farm_card.html" with size="full" farm=farm cards=cards %}
{% endblock %}

farm/templates/plotDetailsModal.html
<div class="modal" id="edit-plot-modal">
    <input id="edit-plot-id" type="hidden">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" id="edit-plot-header">
                <h5 class="modal-title">Plot Details</h5>
                <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Plot Name</span>
                    </div>
                    <input class="form-control" id="edit-plot-name" type="text">
                </div>
                {% if plotTypes %}
                    <div class="input-group mb-3">
                        <select class="custom-select" id="edit-plot-type" required="required">
                            <option selected>Plot Type</option>
                            {% for plotType in plotTypes %}
                            <option value="{{ plotType.0 }}">{{ plotType.1|title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Plot Description</span>
                    </div>
                    <textarea aria-label="Plot description" class="form-control" id="edit-plot-description"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" onclick="savePlotDetails({{ plot.id }})" type="button">Save</button>
            </div>
        </div>
    </div>
</div>

farm/templates/plot_details_modal.html
<div class="modal" id="edit-plot-modal" data-plot-id="">
    <input id="edit-plot-id" type="hidden">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" id="edit-plot-header">
                <h5 class="modal-title">Plot Details</h5>
                <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Plot Name</span>
                    </div>
                    <input class="form-control" id="edit-plot-name" type="text">
                </div>
                {% if plotTypes %}
                    <div class="input-group mb-3">
                        <select class="custom-select" id="edit-plot-type" required="required">
                            <option selected>Plot Type</option>
                            {% for plotType in plotTypes %}
                            <option value="{{ plotType.0 }}">{{ plotType.1|title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Plot Description</span>
                    </div>
                    <textarea aria-label="Plot description" class="form-control" id="edit-plot-description"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" onclick="savePlotDetails()" type="button">Save</button>
            </div>
        </div>
    </div>
</div>

farm/templates/plot_grouped_summary.html
{% extends 'layout/grouped_summary.html' %}

{% block summary %}
    <div id="map" class="card map map-lg"></div>
{% endblock %}

farm/templates/plot_overview.html
{% extends 'pageLayout.html' %}
{% load static %}
{% load common %}

{% block includes %}
    {% include "maps.html" %}
{% endblock %}

{% block javascript %}
    <script src="{% static './plot/style/plotColors.js' %}"></script>
    <script src="{% static 'js/maps/initmap.js' %}" type="text/javascript"></script>
    <script src="{% static './farm/js/plotOverview.js' %}" type="text/javascript"></script>
{% endblock %}

{% block pageContent %}
    {{ farm.location.getCoordinates | json_script:"farm-location" }}
    {{ farm.id | json_script:"farm-id" }}
    {{ plots | json_script:"plots-data" }}
    {% csrf_token %}
    {% include 'plot_overview_card.html' with size="full" plots=farm.plot_set.all %}
    {% include 'plot_details_modal.html' with plot=plot %}
{% endblock %}

farm/templates/plot_overview_card.html
{% extends 'uiElements/card.html' %}

{% block header %}
    {% include 'farm_header.html' with farm=farm %}
{% endblock %}

{% block content %}
  {% include 'plot_grouped_summary.html' with header="My Plots" group=plots %}
{% endblock %}

farm/templates/plot_sidebar_detail.html
{% extends 'uiElements/accordion_menu.html' %}

{% block title %}
    {{ plot.name }}
{% endblock %}
{% block body %}
    <div id="plot-id-{{ plot.id }}" data-plot-id="{{ plot.id }}"></div>
    {% if plot.description %}
        {{ plot.description }}
    {% endif %}
{% endblock %}