crop/urls.py
from django.urls import path

from crop.views.cropDetails import CropDetails
from crop.views.cropCreator import CropCreator
from taxonomy.views.genus import Genus
from taxonomy.views.species import Species
from crop.views.cropForm import CropForm

urlpatterns = [
    path("add", CropForm.as_view(), name="addCrops"),
    path("", CropDetails.as_view(), name="listCrops"),
    path("create", CropCreator.as_view(), name="addCrop"),
    path("species/create", Species.as_view(), name="addSpecies"),
    path("genus/create", Genus.as_view(), name="addGenus"),
]

seedbank/urls.py
from django.urls import path

from seedbank.views.seedbankdetail import SeedbankDetail

urlpatterns = [
    path("", SeedbankDetail.as_view(), name="seedbank"),
]

soli/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework import routers

from farm.views import farmApi
from farm.views.farmApi import FarmApi

from soli import settings

urlpatterns = [
    path("", include("account.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("plot/", include("plot.urls")),
    path("myfarms/", include("farm.urls")),
    path("calendar/", include("schedule.urls")),
    path("seedbank/", include("seedbank.urls")),
    path("herd/", include("herd.urls")),
    path("admin/crop/", include("crop.urls")),
    path("crop/", include("crop.urls")),
    path("layout/", include(("layout.urls"))),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seedbank/models/seedbank.py
from datetime import datetime

from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models

from crop.models.crop import Crop


class Seedbank(models.Model):
    class Meta:
        db_table = "seedbank"
        app_label = "seedbank"
        unique_together = ["user", "crop", "year"]

    crop = models.ForeignKey(Crop, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    year = models.IntegerField(default=datetime.now().year)
    company = models.CharField(blank=True, null=True, max_length=30)

    def __str__(self):
        return f"{self.crop.__str__()} ({self.year})"

    def get_user_seedbank(self, user):
        seedbank = {}
        for seed in Seedbank.objects.filter(user=user, quantity__gt=0):
            crop = seed.crop
            species = crop.species

            if species not in seedbank:
                seedbank[species] = {}

            if crop not in seedbank[species]:
                seedbank[species][crop] = []

            seedbank[species][crop].append(seed)
        return seedbank

seedbank/views/seedbankdetail.py
from seedbank.models.seedbank import Seedbank
from soli.views.authenticatedPageView import AuthenticatedPageView
from taxonomy.models.species import Species


class SeedbankDetail(AuthenticatedPageView):
    def get(self, request):
        self.construct(request)

        self.context["seedbank"] = Seedbank().get_user_seedbank(self.user)
        self.context["species"] = Species.objects.filter(
            crop__seedbank__user=self.user, crop__seedbank__quantity__gt=0
        ).distinct()
        self.context["seedbank_table_columns"] = ["Year", "Company", "Quantity"]

        return self.render("seedbank.html")

    def post(self, request):
        self.construct(request)

seedbank/templates/seed_details.html
{% extends 'uiElements/card.html' %}

{% block header %}
  <h4>
    {{ seed }}
  </h4>
{% endblock %}

{% block content %}
    {{ seed.quantity }}
{% endblock %}

seedbank/templates/seedbank.html
{% extends 'pageLayout.html' %}
{% load static %}

{% block pageContent %}
    {% include 'seedbank_grouped_summary.html' with seedbank=seedbank header="My Seeds" group=species %}
{% endblock %}

seedbank/templates/seedbank_grouped_summary.html
{% extends 'layout/grouped_summary.html' %}

{% block summary %}
    {% for species, crops in seedbank.items %}
        {% for crop in crops %}
            {% include 'seedset.html' with size='full' crop=crop %}
        {% endfor %}
    {% endfor %}
{% endblock %}

seedbank/templates/seedset.html
{% extends 'uiElements/card.html' %}

{% block header %}
  <h4>
    {{ crop }}
  </h4>
{% endblock %}

{% block content %}
    {% include 'seedset_table.html' with crop=crop %}
{% endblock %}

seedbank/templates/seedset_table.html
{% extends 'uiElements/table/table.html' %}

{% block header %}
    {% include 'uiElements/table/table_header.html' with columns=seedbank_table_columns %}
{% endblock %}
{% block body %}
    {% for seed in crop.seedbank_set.all|dictsortreversed:"year" %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ seed.year }}</td>
        <td>{{ seed.company|default:"" }}</td>
        <td>{{ seed.quantity }}</td>
      </tr>
    {% endfor %}
{% endblock %}